$(document).ready(function () {indexDict['en'] = [{ "title" : "Secure Web Gateway ", 
"url" : "328-secure-web-gateway.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Secure Web Gateway...", 
"body" : "Secure Web Gateway " }, 
{ "title" : "Remote Browser Isolation ", 
"url" : "325-remote-browser-isolation.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Remote Browser Isolation...", 
"body" : "Remote Browser Isolation " }, 
{ "title" : "Email Isolation ", 
"url" : "329-email-isolation.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Email Isolation...", 
"body" : "Email Isolation " }, 
{ "title" : "Cloud Access Security Broker (CASB) ", 
"url" : "7256-cloud-access-security-broker--casb-.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Cloud Access Security Broker (CASB)...", 
"body" : "Cloud Access Security Broker (CASB) " }, 
{ "title" : "About Inline CASB ", 
"url" : "7262-about-inline-casb.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ About Inline CASB ", 
"snippet" : "Inline CASB provides visibility into the cloud applications your users are accessing through the Menlo Cloud Proxy and helps prevent accidental, or intentional, data exposure. Inline CASB addresses these major areas of concern around cloud app usage: Cloud App Visibility & Discovery Visualize cloud ...", 
"body" : "Inline CASB provides visibility into the cloud applications your users are accessing through the Menlo Cloud Proxy and helps prevent accidental, or intentional, data exposure. Inline CASB addresses these major areas of concern around cloud app usage: Cloud App Visibility & Discovery Visualize cloud app usage and associated risk across your organization Easy-to-navigate SaaS usage dashboards and detailed reporting Support for over 200 cloud apps and services Control Sanctioned and Unsanctioned Cloud Apps Monitor and control user sessions in real-time Block or limit specific functions within a cloud application — such as “login”, “share”, “search”, “upload”, “download”, “create” Enforce access to cloud apps through isolation Threat Protection Identify and block malware within SaaS applications Isolate document downloads from cloud apps " }, 
{ "title" : "CASB Application Categories ", 
"url" : "7265-casb-application-categories.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ CASB Application Categories ", 
"snippet" : "Cloud application categories include: Cloud File Sharing E-commerce and Accounting Human Capital Management Identity and Access Management Instant Messaging IT Services and Hosting Office Document and Productivity Payment Sales and CRM Social Networking Streaming Media Web Meetings Webmail...", 
"body" : "Cloud application categories include: Cloud File Sharing E-commerce and Accounting Human Capital Management Identity and Access Management Instant Messaging IT Services and Hosting Office Document and Productivity Payment Sales and CRM Social Networking Streaming Media Web Meetings Webmail " }, 
{ "title" : "How CASB works ", 
"url" : "7295-how-casb-works.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ How CASB works ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "How to enable CASB for your account ", 
"url" : "7297-how-to-enable-casb-for-your-account.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ How to enable CASB for your account ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Inline CASB policy reinforcement ", 
"url" : "7299-inline-casb-policy-reinforcement.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ Inline CASB policy reinforcement ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Get started with Inline CASB ", 
"url" : "7301-get-started-with-inline-casb.html", 
"breadcrumbs" : "Documentation Hub \/ Cloud Access Security Broker (CASB) \/ Get started with Inline CASB ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Data Lost Prevention (DLP) ", 
"url" : "7258-data-lost-prevention--dlp-.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Data Lost Prevention (DLP)...", 
"body" : "Data Lost Prevention (DLP) " }, 
{ "title" : "Zero Trust Private Access (ZTPA) ", 
"url" : "7257-zero-trust-private-access--ztpa-.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Zero Trust Private Access (ZTPA)...", 
"body" : "Zero Trust Private Access (ZTPA) " }, 
{ "title" : "Cloud Firewall ", 
"url" : "7259-cloud-firewall.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Cloud Firewall...", 
"body" : "Cloud Firewall " }, 
{ "title" : "Release Notes - All ", 
"url" : "7303-release-notes---all.html", 
"breadcrumbs" : "Documentation Hub \/ ", 
"snippet" : "Release Notes - All...", 
"body" : "Release Notes - All " }, 
{ "title" : "Web Isolation Release Notes ", 
"url" : "7304-web-isolation-release-notes.html", 
"breadcrumbs" : "Documentation Hub \/ Release Notes - All \/ Web Isolation Release Notes ", 
"snippet" : "Public Cloud (SaaS) Web Isolation Private Cloud (On-Prem virtual appliance) Web Isolation...", 
"body" : "Public Cloud (SaaS) Web Isolation Private Cloud (On-Prem virtual appliance) Web Isolation " }, 
{ "title" : "Email Isolation Release Notes ", 
"url" : "7305-email-isolation-release-notes.html", 
"breadcrumbs" : "Documentation Hub \/ Release Notes - All \/ Email Isolation Release Notes ", 
"snippet" : "Public Cloud (SaaS) Email Isolation Private Cloud (On-Prem virtual appliance) Email Isolation...", 
"body" : "Public Cloud (SaaS) Email Isolation Private Cloud (On-Prem virtual appliance) Email Isolation " }, 
{ "title" : "Menlo Connect Release Notes ", 
"url" : "7308-menlo-connect-release-notes.html", 
"breadcrumbs" : "Documentation Hub \/ Release Notes - All \/ Menlo Connect Release Notes ", 
"snippet" : "...", 
"body" : "" }
]
$(document).trigger('search.ready');
});